language: node_js
node_js:
  - "6"
script: npm run build --prod
cache:
  directories:
    - node_modules
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: www
  fqdn: today.leward.eu
  on:
    branch: master
